language: perl
perl:
- 5.18
- 5.16
- 5.14
- 5.12
- 5.10
- 5.8

install:
- cpanm --quiet --notest
  Pegex
  Devel::Cover::Report::Coveralls

script:
- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine
  PERL5LIB=../testml-pm/lib
  prove -lv t/
- cover

after_success:
- cover -report coveralls
